core/cart/api/rest/v1/urls.py
from django.urls import path
from . import views

app_name="api-rest"

urlpatterns = [
    path("list-product/", views.ListProductView.as_view(), name="list-product"),
    path("add-product/", views.AddProductView.as_view(), name="add-product"),
    path("update-product/", views.UpdateProductView.as_view(), name="update-product"),
    path("delete-product/", views.DeleteProductView.as_view(), name="delete-product"),
]

core/cart/urls.py
from django.urls import path, include
from . import views


app_name = "cart"
urlpatterns = [
    path("cart_summary/", views.CartSummaryView.as_view(), name="cart-summary"),
    path("add-product/", views.AddProductView.as_view(), name="add-product"),
    path("update-product-quantity/", views.UpdateProductQtyView.as_view(), name="update-product-qty"),
    path("delete-product/", views.DeleteProductView.as_view(), name="delete-product"),
    path("api-cart/", include("cart.api.rest.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="Caspian Sofa Project Api",
        default_version="v1",
        description="Caspian Sofa Projects",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="Fahim@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("dashboard/", include("dashboard.urls")),


    path("swagger/",schema_view.with_ui("swagger", cache_timeout=0), name="shema-swagger-ui"),
    path("redoc/",schema_view.with_ui("redoc", cache_timeout=0),name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/order/urls.py
from django.urls import path
from . import views


app_name= "order"

urlpatterns = [
    path("validation/coupon/", views.ValidationCouponView.as_view(), name="validation-coupon"),
    path("checkout/", views.OrderCheckoutView.as_view(), name="checkout"),
    path("completed/", views.OrderCompletedView.as_view(), name="completed"),
    path("failed/", views.OrderFailedView.as_view(), name="failed"),
]

core/shop/urls.py
from django.urls import path
from . import views


app_name="shop"

urlpatterns =[
    path("product/grid/", views.ProductGridView.as_view(), name="product-grid"),
    path("product/detail/<int:pk>/", views.ProductDetailView.as_view(), name="product-detail"),
]

core/cart/models.py
from django.db import models

# Create your models here.

class CartModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email


    def calculate_total_price(self):
        return sum(item.product.get_price_after_sale() * item.quantity for item in self.cart_items.all())

class CartItemModel(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE, related_name="cart_items")
    product = models.ForeignKey("shop.SofaModel", on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=0)
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.name}{self.product.id}"

core/cart/api/rest/v1/views.py
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, UpdateAPIView, DestroyAPIView, ListAPIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from .serializers import ProductCartSerializer, DeleteProductSerializer, ListProductSerializer
from rest_framework import status
from cart.cart import CartSession
from cart.models import CartModel, CartItemModel


class ListProductView(ListAPIView): 
    serializer_class = ListProductSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        try:
            cart = CartModel.objects.get(user=user)
        except CartModel.DoesNotExist:
            return CartItemModel.objects.none()
        return CartItemModel.objects.filter(cart=cart)
        

class AddProductView(CreateAPIView):
    serializer_class = ProductCartSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        cart = CartSession(session=request.session)
        if serializer.is_valid(raise_exception=True):
            product_id = serializer.validated_data["product_id"]
            quantity = serializer.validated_data["quantity"]
            if product_id and quantity:
                cart.add_product(product_id, quantity)
                return Response({"detail":"محصول شما با موفقیت به سبد خرید اضافه شد ."}, status=status.HTTP_200_OK)
            if request.user.is_authenticated:
                cart.merge_session_cart_in_db(request.user)
            return Response({"detail":"خطایی رخ داد لطفا دقایقی بعد اقدام کنید .."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)  
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class UpdateProductView(UpdateAPIView):
    serializer_class = ProductCartSerializer
    permission_classes = [IsAuthenticated]

    def put(self,request):
        serializer = self.serializer_class(data=request.data)
        cart = CartSession(session=request.session)

        if serializer.is_valid(raise_exception=True):
            product_id = serializer.validated_data["product_id"]
            quantity = serializer.validated_data["quantity"]

            if product_id and quantity:
                cart.update_product_qty(product_id, quantity)
                return Response({"detail":"تعداد سفارش شما با موفقیت تغییر کرد."}, status=status.HTTP_200_OK)
            if request.user.is_authenticated:
                cart.merge_session_cart_in_db(request.user)
            return Response({"detail":"خطایی رخ داد دقایقی بعد مجددا تلاش کنید."}, status=status.HTTP_400_BAD_REQUEST)

        return Response(serializer.errors, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

class DeleteProductView(DestroyAPIView):
    serializer_class = DeleteProductSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request):
        data = request.data
        serializer = self.serializer_class(data=data)
        cart = CartSession(session=request.session)
        
        if serializer.is_valid(raise_exception=True):
            product_id = serializer.validated_data["product_id"]

            if product_id:
                cart.delete_product(product_id)
                return Response({"detail":"محصول شما با موفقیت از سبد خرید حذف شد ."}, status=status.HTTP_200_OK)
            if request.user.is_authenticated:
                cart.merge_session_cart_in_db(request.user)
            return Response({"detail":"خطایی رخ داد لطفا دقایقی بعد اقدام کنید .."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(serializer.error_messages, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

core/cart/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .cart import CartSession
from cart.models import CartModel, CartItemModel
from django.http import JsonResponse
# Create your views here.


class CartSummaryView(LoginRequiredMixin, TemplateView):
    template_name = "cart/cart_summary.html"

    
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        cart = CartSession(session=self.request.session)
        context["cart_items"] = cart.get_cart_items()
        context["total_quantity"] = cart.get_total_quantity()
        total_payment_price = cart.get_total_payment_price()
        context["total_payment_price"] = total_payment_price
        total_tax = round((cart.get_total_price()*10)/100)
        context["total_tax"] = total_payment_price - (total_payment_price - total_tax)
        context["total_price"] = cart.get_total_price()
        return context
    
class AddProductView(CreateView):
    
    def post(self, request, *args, **kwargs):
        cart = CartSession(session=request.session)
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("qty")
        if product_id and quantity:
            cart.add_product(product_id, quantity)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)

        return JsonResponse({"cart":cart.get_cart_dict(), "total_quantity":cart.get_total_quantity()})
    
class DeleteProductView(DeleteView):
    
    def post(self, request, *args, **kwargs):
        cart = CartSession(session=request.session)
        product_id = request.POST.get("product_id")
        if product_id:
            cart.delete_product(product_id)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)

        return JsonResponse({"cart":cart.get_cart_dict(), "total_quantity":cart.get_total_quantity()})

class UpdateProductQtyView(UpdateView):
    
    def post(self, request, *args, **kwargs):
        cart = CartSession(session=request.session)
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("qty")
        if product_id and quantity:
            cart.update_product_qty(product_id, quantity)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)

        return JsonResponse({"cart":cart.get_cart_dict(), "total_quantity":cart.get_total_quantity()})
    

core/templates/cart/cart_summary.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block extra_css %}{% endblock %}

{% block content %}


<div class="container">
    <div class="row mb-5">
      <form class="col-md-12" method="post">
        <div class="site-blocks-table">
          <table class="table">
            <thead>
              <tr>
                <th class="product-thumbnail">تصویر</th>
                <th class="product-name">محصول</th>
                <th class="product-price">مبلغ</th>
                <th class="product-quantity">تعداد</th>
                <th class="product-total">جمع</th>
                <th class="product-remove">اعمال</th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart_items %}
              <tr>
                <td class="product-thumbnail">
                  <a href="{% url 'shop:product-detail' pk=item.product_obj.id %}"><img src="{{ item.product_obj.image.url }}" alt="Image" class="img-fluid"></a>
                </td>
                <td class="product-name">
                  <a href="{% url 'shop:product-detail' pk=item.product_obj.id %}" style="text-decoration: none;" class="h5 text-black">{{ item.product_obj.name }}</a>
                </td>
                <td>{{ item.product_obj.get_price_after_sale|intcomma }}</td>
                <td>
                  <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                    <div class="input-group-prepend">
                      <button class="btn btn-outline-black decrease" onclick="MinusProductToCart('{{ item.product_obj.id }}',  $(this).closest('.quantity-container').find('.quantity-amount').val())" type="button">&minus;</button>
                    </div>
                    <input type="text" class="form-control text-center quantity-amount" id="quantity-product" value="{{ item.quantity }}" aria-label="Example text with button addon" aria-describedby="button-addon1" readonly>
                    <div class="input-group-append">
                      <button onclick="PlusProductToCart('{{ item.product_obj.id }}', $(this).closest('.quantity-container').find('.quantity-amount').val())" class="btn btn-outline-black increase" type="button">&plus;</button>
                    </div>
                  </div>
                </td>
                <td>{{ item.product_obj.get_price_after_sale|intcomma }}</td>
                <td><button onclick="DeleteProductToCart('{{ item.product_obj.id }}')" type="button" class="btn btn-black btn-sm">X</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </form>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="row mb-5">
          <div class="col-md-6">
            <a href="{% url 'shop:product-grid' %}" class="btn btn-outline-black btn-sm btn-secondary">بازگشت به صفحه محصولات</a>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <label class="text-black h4" for="coupon">کدتخفیف</label>
            <p>کد تخفیف خود را وارد کنید .</p>
          </div>
          <div class="col-md-8 mb-3 mb-md-0">
            <input type="text" class="form-control py-3" id="coupon" placeholder="کدتخفیف">
          </div>
          <div class="col-md-4">
            <button class="btn btn-primary"> اعمال تخفیف</button>
          </div>
        </div>
      </div>
      <div class="col-md-6 pl-5">
        <div class="row justify-content-end">
          <div class="col-md-7">
            <div class="row">
              <div class="col-md-12 text-right border-bottom mb-5">
                <h3 class="text-black h4 text-uppercase">جمع کل سبد خرید</h3>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <span class="text-black">مبلغ محصولات :</span>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">{{ total_price|intcomma }}</strong>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <span class="text-black">مالیات :</span>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">{{ total_tax|intcomma }}</strong>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <span class="text-black">درصد تخفیف :</span>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">{{ total_tax|intcomma }}</strong>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <span class="text-black">مبلغ کسری :</span>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">{{ total_tax|intcomma }}</strong>
              </div>
            </div>
            <div class="row mb-5">
              <div class="col-md-6">
                <span class="text-black">جمع کل :</span>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">{{ total_payment_price|intcomma }}</strong>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <form action="{% url 'order:checkout' %}">
                  <button class="btn btn-black btn-lg py-3 btn-secondary" type="submit">نهایی کردن سفارش</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

{% block extra_js%}{% endblock %}