core/cart/urls.py
from django.urls import path, include
from . import views


app_name = "cart"
urlpatterns = [
    path("cart_summary/", views.CartSummaryView.as_view(), name="cart-summary"),
    path("add-product/", views.AddProductView.as_view(), name="add-product"),
    path("update-product-quantity/", views.UpdateProductQtyView.as_view(), name="update-product-qty"),
    path("delete-product/", views.DeleteProductView.as_view(), name="delete-product"),
    path("api-cart/", include("cart.api.rest.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="Caspian Sofa Project Api",
        default_version="v1",
        description="Caspian Sofa Projects",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="Fahim@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("dashboard/", include("dashboard.urls")),


    path("swagger/",schema_view.with_ui("swagger", cache_timeout=0), name="shema-swagger-ui"),
    path("redoc/",schema_view.with_ui("redoc", cache_timeout=0),name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/dashboard/urls.py
from django.urls import path, include
from . import views


app_name="dashboard"

urlpatterns =[
    path("home/", views.DashBoardHomeView.as_view(), name="home"),
    
    path("admin/", include("dashboard.admins.urls")),
    path("customer/", include("dashboard.customers.urls")),
]

core/website/urls.py
from django.urls import path
from . import views

app_name="website"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("contact/", views.ContactPageView.as_view(), name="contact"),
]   

core/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="Untree.co">
	<link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

	<meta name="description" content="" />
	<meta name="keywords" content="bootstrap, bootstrap4" />

	<!-- Bootstrap CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
	<link href="{% static 'css/tiny-slider.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
	<link rel="stylesheet" href="{% static 'toastify/toastify.css' %}">
	{% block extra_css %}{% endblock %}
	<title>مبلمان کاسپین</title>
</head>

<body dir="rtl">

	<!-- Start Header/Navigation -->
	<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

		<div class="container">
			<a class="navbar-brand" href="{% url 'website:index' %}">مبلمان کاسپین<span>.</span></a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni"
				aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" style="flex-grow: 0;" id="navbarsFurni">
				<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
					<li {% if request.resolver_match.view_name == 'website:index' %} class="nav-item active" {% endif %}>
						<a class="nav-link" href="{% url 'website:index' %}">خانه</a>
					</li>

					{% if request.user.is_authenticated is not True %}
					<li {% if request.resolver_match.view_name == 'accounts:login' %} class="active" {% endif %}><a
						class="nav-link" href="{% url 'accounts:login' %}">ورود</a></li>
					{% endif %}
					<li {% if request.resolver_match.view_name == 'shop:product-grid' %} class="active" {% endif %}><a
							class="nav-link" href="{% url 'shop:product-grid' %}">محصولات</a></li>
					<li {% if request.resolver_match.view_name == 'website:about' %} class="active" {% endif %}><a
							class="nav-link" href="{% url 'website:about' %}">درباره ما</a></li>
					<li {% if request.resolver_match.view_name == 'website:contact' %} class="active" {% endif %}><a
							class="nav-link" href="{% url 'website:contact' %}">ارتباط با ما</a></li>
					<li><a class="nav-link" href="services.html">خدمات ما</a></li>
					<li><a class="nav-link" href="blog.html">اخبار</a></li>

				</ul>

				<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
					{% if request.user.is_authenticated %}
						<li><a class="nav-link" href="{% url 'dashboard:home' %}"><img src="{% static 'img/user.svg' %}"></a></li>
					{% endif %}
					<li><a class="nav-link" href="{% url 'cart:cart-summary' %}"><img src="{% static 'img/cart.svg' %}"><span>{{ cart.get_total_quantity }}</span></a></li>
				</ul>
			</div>
		</div>w
	</nav>
	<!-- End Header/Navigation -->

	{% block content %}
	{% endblock %}

	<!-- Start Footer Section -->
	<footer class="footer-section" style="    margin-top: 5rem;">
		<div class="container relative">

			<div class="sofa-img">
				<img src="{% static 'img/sofa.png' %}" alt="Image" class="img-fluid">
			</div>

			<div class="row" style="justify-content: flex-end;">
				<div class="col-lg-8">
					<div class="subscription-form">
						<h3 class="d-flex align-items-center"><span class="me-1"><img
									src="{% static 'img/envelope-outline.svg' %}" alt="Image"
									class="img-fluid"></span><span>برای دریافت اخبار جدید ایمیل خود را ارسال
								کنید.</span></h3>

						<form action="#" class="row g-3">
							<div class="col-auto">
								<input type="text" class="form-control" placeholder="نام کامل خود را وارد کنید">
							</div>
							<div class="col-auto">
								<input type="email" class="form-control" placeholder="ایمیل خود را وارد کنید">
							</div>
							<div class="col-auto">
								<button class="btn btn-primary">
									<span class="fa fa-paper-plane"></span>
								</button>
							</div>
						</form>

					</div>
				</div>
			</div>

			<div class="row g-5 mb-5">
				<div class="col-lg-4">
					<div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">مبلمان کاسپین<span>.</span></a>
					</div>
					<p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus
						malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.
						Pellentesque habitant</p>

					<ul class="list-unstyled custom-social">
						<li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
						<li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
						<li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
						<li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
					</ul>
				</div>

				<div class="col-lg-8">
					<div class="row links-wrap">
						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">About us</a></li>
								<li><a href="#">Services</a></li>
								<li><a href="#">Blog</a></li>
								<li><a href="#">Contact us</a></li>
							</ul>
						</div>

						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">Support</a></li>
								<li><a href="#">Knowledge base</a></li>
								<li><a href="#">Live chat</a></li>
							</ul>
						</div>

						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">Jobs</a></li>
								<li><a href="#">Our team</a></li>
								<li><a href="#">Leadership</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>

						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">Nordic Chair</a></li>
								<li><a href="#">Kruzo Aero</a></li>
								<li><a href="#">Ergonomic Chair</a></li>
							</ul>
						</div>
					</div>
				</div>

			</div>

			<div class="border-top copyright">
				<div class="row pt-4">
					<div class="col-lg-6">
						<p class="mb-2 text-center text-lg-start">Copyright &copy;
							<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash;
							Designed with love by <a href="https://untree.co">Untree.co</a> Distributed By <a
								hreff="https://themewagon.com">ThemeWagon</a>
							<!-- License information: https://untree.co/license/ -->
						</p>
					</div>

					<div class="col-lg-6 text-center text-lg-end">
						<ul class="list-unstyled d-inline-flex ms-auto">
							<li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
							<li><a href="#">Privacy Policy</a></li>
						</ul>
					</div>

				</div>
			</div>

		</div>
	</footer>
	<!-- End Footer Section -->


	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'js/tiny-slider.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
	<script src="{% static 'toastify/toastify-es.js' %}"></script>
	<script src="{% static 'toastify/toastify.js' %}"></script>

	{% block extra_js %}{% endblock %}
	{% include 'messages.html' %}
	<script>
		function AddProductToCart(product_id, qty){
			$.ajax({
				type:"POST",
				url: "{% url 'cart:add-product' %}",
				data:{
					csrfmiddlewaretoken:"{{ csrf_token }}",
					product_id :product_id,
					qty :qty
				},
				success: function(response){
					window.location.reload()
				},
				error: function (err,errmsg,xhr) {
					console.log(err)
				}
			});
		}
		function DeleteProductToCart(product_id){
			$.ajax({
				type:"POST",
				url: "{% url 'cart:delete-product' %}",
				data:{
					csrfmiddlewaretoken:"{{ csrf_token }}",
					product_id :product_id
				},
				success: function(response){
					window.location.reload()
				},
				error: function (err,errmsg,xhr) {
					console.log(err)
				}
			});
		}
		function PlusProductToCart(product_id, qty){
			quantity = parseInt(qty) + 1
			$.ajax({
				type:"POST",
				url: "{% url 'cart:update-product-qty' %}",
				data:{
					csrfmiddlewaretoken:"{{ csrf_token }}",
					product_id :product_id,
					qty:quantity
				},
				success: function(response){
					window.location.reload()
				},
				error: function (err,errmsg,xhr) {
					console.log(err)
				}
			});
		}
		function MinusProductToCart(product_id, qty){
			quantity = parseInt(qty) - 1
			$.ajax({
				type:"POST",
				url: "{% url 'cart:update-product-qty' %}",
				data:{
					csrfmiddlewaretoken:"{{ csrf_token }}",
					product_id :product_id,
					qty:quantity
				},
				success: function(response){
					window.location.reload()
				},
				error: function (err,errmsg,xhr) {
					console.log(err)
				}
			});
		}
	</script>
</body>
</html>

core/templates/messages.html
{% if messages %}

    {% for message in messages %}
    
        <script>
            Toastify({
                text:`{{ message|safe }}`,
                className: `{{ message.tags }}`,
                style: {
                    background:"green"
                }
            }).showToast();
        </script>
    
    {% endfor %}

{% endif %}

{% if form.errors %}

    <div class="alert alert-error">
        <ul>
            {% for field in form%}
                {% if field.errors %}
                    {% for error in field.errors %}
                    <script>
                        Toastify({
                            text:`{{ error|escape }}`,
                            className: `error`,
                            style: {
                                background : 'red',
                            }
                        }).showToast();
                    </script>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
        {% if field.non_field_errors %}
            <script>
                Toastify({
                    text:`{{ form.non_field_errors.as_text }}`,
                    className: `error`,
                    style:{
                        background:"red",
                    }

                }).showToast();
            </script>
        {% endif %}
    </div>
{% endif %}