core/cart/urls.py
from django.urls import path, include
from . import views


app_name = "cart"
urlpatterns = [
    path("cart_summary/", views.CartSummaryView.as_view(), name="cart-summary"),
    path("add-product/", views.AddProductView.as_view(), name="add-product"),
    path("update-product-quantity/", views.UpdateProductQtyView.as_view(), name="update-product-qty"),
    path("delete-product/", views.DeleteProductView.as_view(), name="delete-product"),
    path("api-cart/", include("cart.api.rest.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="Caspian Sofa Project Api",
        default_version="v1",
        description="Caspian Sofa Projects",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="Fahim@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("dashboard/", include("dashboard.urls")),


    path("swagger/",schema_view.with_ui("swagger", cache_timeout=0), name="shema-swagger-ui"),
    path("redoc/",schema_view.with_ui("redoc", cache_timeout=0),name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/order/urls.py
from django.urls import path
from . import views


app_name= "order"

urlpatterns = [
    path("validation/coupon/", views.ValidationCouponView.as_view(), name="validation-coupon"),
    path("checkout/", views.OrderCheckoutView.as_view(), name="checkout"),
    path("completed/", views.OrderCompletedView.as_view(), name="completed"),
    path("failed/", views.OrderFailedView.as_view(), name="failed"),
]

core/shop/urls.py
from django.urls import path
from . import views


app_name="shop"

urlpatterns =[
    path("product/grid/", views.ProductGridView.as_view(), name="product-grid"),
    path("product/detail/<int:pk>/", views.ProductDetailView.as_view(), name="product-detail"),
]

core/order/models.py
from django.db import models

# Create your models here.

class OrderStatusType(models.IntegerChoices):
    pending = 1, "در انتظار پرداخت"
    processing  = 2, "درحال پردازش"
    shipped  = 3, "ارسال شده"
    delivered  = 4, "تحویل داده شده"
    canceled  = 5, "لغو شده"

class CouponModel(models.Model):
    code = models.CharField(max_length=200)
    discount_percent = models.IntegerField(default=0)
    max_limit_usage = models.IntegerField(default=0)
    used_by = models.ManyToManyField("accounts.User", blank=True, null=True) 
    expiration_date = models.DateTimeField(blank=True, null=True)
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.code


class UserAddressModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    
    address = models.CharField(max_length=250)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user.email}-{self.address}"




class OrderModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.PROTECT)
    total_price = models.DecimalField(max_digits=12, decimal_places=0, default=0)
    coupon = models.ForeignKey(CouponModel, on_delete=models.PROTECT, null=True, blank=True)
    status = models.IntegerField(choices=OrderStatusType.choices, default=OrderStatusType.pending.value)

    address = models.CharField(max_length=250)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50)

    payment = models.ForeignKey("payment.PaymentModel", on_delete=models.SET_NULL, null=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return f"{self.user.email}-{self.id}"
    
    def calculate_total_price(self):
        return sum(item.price * item.quantity for item in self.order_items.all())

class OrderItemModel(models.Model):
    order= models.ForeignKey(OrderModel, on_delete=models.CASCADE, related_name="order_items")
    product = models.ForeignKey("shop.SofaModel", on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=12, decimal_places=0, default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

core/order/forms.py
from django import forms
from .models import UserAddressModel, CouponModel
from datetime import timezone
class CheckOutForm(forms.Form):
    address_id = forms.IntegerField(required=True)
    coupon = forms.CharField(max_length=100, required=False)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(CheckOutForm, self).__init__(*args, **kwargs)


    def clean_address_id(self):
        address_id = self.cleaned_data.get("address_id")

        user = self.request.user

        try:
            address = UserAddressModel.objects.get(id=address_id, user=user)
        except UserAddressModel.DoesNotExist:
            raise forms.ValidationError("آدرسی ثبت نشده است .")
        
        return address

    def clean_coupon(self):
        code = self.cleaned_data.get("coupon")

        if code == "":
            return None
        
        user = self.request.user

        try :
            coupon = CouponModel.objects.get(code=code)
        except CouponModel.DoesNotExist:
            raise forms.ValidationError("کد تخفیف وارد شده وجود ندارد ..")

        if coupon:

            if coupon.used_by.count() >= coupon.max_limit_usage:
                raise forms.ValidationError("تعداد استفاده کنندگان از تخفیف به اتمام رسیده است ..")

            if coupon.expiration_date and coupon.expiration_date < timezone.now():
                raise forms.ValidationError("زمان استفاده از تخفیف به اتمام رسیده ..")
            
            if user in coupon.used_by.all():
                raise forms.ValidationError("این کد قبلا توسط شما استفاده شده است .")

        return coupon

core/order/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic import FormView, TemplateView, View
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CheckOutForm
from .models import OrderItemModel, OrderModel, CouponModel, UserAddressModel
from datetime import timezone
from cart.models import CartModel
from payment.zarinpal_client import ZarinPalBox
from payment.models import PaymentModel, PaymentStatusType
from django.http import JsonResponse
from cart.cart import CartSession
from decimal import Decimal
# Create your views here.

class OrderCheckoutView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    template_name = "order/checkout.html"
    success_url = reverse_lazy("order:successfully")
    form_class = CheckOutForm

    def get_form_kwargs(self):
        kwargs= super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs
        
    def form_valid(self, form):
        user = self.request.user
        cleaned_data = form.cleaned_data
        address = cleaned_data["address_id"]
        coupon = cleaned_data["coupon"]
        cart = CartModel.objects.get(user=user)
        order= self.create_order(address)
        self.create_order_items(order,cart)
        self.clear_cart(cart)
        total_price = order.calculate_total_price()
        self.apply_coupon(coupon, order, user, total_price)
        order.save()
        return redirect(self.create_payment_url(order))
        
    def create_order(self, address):
        order = OrderModel.objects.create(
            user=self.request.user,
            address=address.address,
            state=address.state,
            city= address.city,
            zip_code = address.zip_code
        )
        return order

    def create_order_items(self, order, cart):
        for item in cart.cart_items.all():
            OrderItemModel.objects.create(
                order = order,
                product=item.product,
                quantity=item.quantity,
                price=item.product.price
            )

    def apply_coupon(self, coupon, order, user, total_price):
        if coupon:
            discount_amount = round((total_price * Decimal(coupon.discount_percent / 100)))
            total_price -= discount_amount

            order.coupon = coupon
            coupon.used_by.add(user)
            coupon.save()
        order.total_price = total_price

    def get_context_data(self, **kwargs):
        cart= CartModel.objects.get(user=self.request.user)
        context= super().get_context_data(**kwargs) 
        context["addressess"] = UserAddressModel.objects.filter(user=self.request.user)
        total_price = cart.calculate_total_price()
        context["total_price"]= total_price
        total_tax = round((total_price * 10)/100)
        context["total_tax"] = total_tax
        total_payment_price = (int(total_price)+int(total_tax))
        context["total_payment_price"] = total_payment_price
        return context


    def create_payment_url(self, order):
        zarinpal = ZarinPalBox()
        response = zarinpal.payment_request(amount=float(order.total_price))
        data= response["data"]
        authority = data["authority"]
        payment_obj = PaymentModel.objects.create(authority_id = authority, amount= order.total_price)

        order.payment = payment_obj
        order.save()

        return zarinpal.generate_payment_url(authority=authority)

    
    def clear_cart(self, cart):
        cart.cart_items.all().delete()
        CartSession(self.request.session).clear()


class OrderCompletedView(LoginRequiredMixin, TemplateView):
    template_name = "order/completed.html"

class OrderFailedView(LoginRequiredMixin, TemplateView):
    template_name = "order/failed.html"


class ValidationCouponView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        code = self.request.POST.get("coupon")

        status_code= 200
        message= "تخفیف با موفقیت اعمال شد ."
        total_price = 0
        total_tax = 0
        total_payment_price = 0

        user= self.request.user
        
        try :
            coupon = CouponModel.objects.get(code=code)
        except CouponModel.DoesNotExist:
            return JsonResponse({"message":"کد تخفیف وارد شده نا معتبر است ."}, status=404)
        
        else:
            if coupon.used_by.count() >= coupon.max_limit_usage:
                status_code, message=403, "محدودیت در تعداد استفاده کارکنان ."

            elif coupon.expiration_date and coupon.expiration_date < timezone.now():
                status_code, message=403, "مدت زمان استفاده از کد تخفیف به پایان رسیده است ."
            
            elif user in coupon.used_by.all():
                status_code, message = 403, "قبلا از کد تخفیف استفاده کرده اید ."

            else:
                cart = CartModel.objects.get(user=user)

                total_price = cart.calculate_total_price()
                total_price = round(total_price - (total_price * (Decimal(coupon.discount_percent)/100)))
                total_tax = round((total_price * 10) / 100)
                total_payment_price = round(total_price + total_tax)


        return JsonResponse({"message":message, "total_tax":total_tax, "total_price":total_price, "total_payment_price":total_payment_price}, status=status_code)

core/templates/order/checkout.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}


{% block extra_css %}{% endblock %}


{% block content %}


<div class="untree_co-section">
    <div class="container">
      <form action="." method="post" id="checkoutform">
      <div class="row">
          {% csrf_token %}
        <div class="col-md-6 mb-5 mb-md-0">
          <h2 class="h3 mb-3 text-black">جزئیات صورتحساب</h2>
          <div class="p-3 p-lg-5 border bg-white">
            <div class="form-group row">
              <div class="col-md-6">
                <label for="c_fname" class="text-black">نام :<span class="text-danger">*</span></label>
                <input type="text"  readonly class="form-control" id="c_fname" name="first_name" value="{{ request.user.user_profile.first_name }}">
              </div>
              <div class="col-md-6">
                <label for="c_fname" class="text-black">نام خانوادگی :<span class="text-danger">*</span></label>
                <input type="text"  readonly class="form-control" id="c_fname" name="last_name" value="{{ request.user.user_profile.last_name }}">
              </div>
            </div>
            <div class="col-md-12">
              <select name="address_id" id="address_id" class="form-select form-select-sm text-center">
                <option selected>انتخاب آدرس تحویل </option>
                {% for address in addressess %}
                <option class="address_id" value="{{ address.id }}">{{ address.address }}-{{ address.state }}-{{ address.city }}-{{ address.zip_code }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group row">
              <div class="col-md-12">
                <label for="c_address" class="text-black">آدرس تحویل : <span class="text-danger">*</span></label>
                <input type="text" readonly class="form-control" id="address_address">
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-6">
                <label for="c_state_country" class="text-black">شهر :<span class="text-danger">*</span></label>
                <input type="text"  readonly  class="form-control" placeholder="تهران" id="address_city" name="c_state_country">
              </div>
              <div class="col-md-6">
                <label for="c_postal_zip" class="text-black">کد پستی :<span class="text-danger">*</span></label>
                <input type="text"  readonly class="form-control" placeholder="۱۲۳۴۵۶۷۸۹۰" id="address_zip_code" name="c_postal_zip">
              </div>
            </div>

            <div class="form-group row mb-5">
              <div class="col-md-6">
                <label for="c_email_address" class="text-black">آدرس ایمیل<span class="text-danger">*</span></label>
                <input type="text"  readonly class="form-control" id="c_email_address" name="" value="{{ request.user.email }}">
              </div>
              <div class="col-md-6">
                <label for="c_phone" class="text-black">شماره تلفن :<span class="text-danger">*</span></label>
                <input type="text"  readonly class="form-control" id="c_phone" name="c_phone" value="{{ request.user.user_profile.phone_number }}">
              </div>
            </div>

            <div class="form-group">
              <label for="c_order_notes" class="text-black">توضیحات تکمیلی :</label>
              <textarea name="c_order_notes" id="c_order_notes" cols="30" rows="5"  class="form-control" placeholder="نظرات و پیشنهاد و توصیه های خود را وارد کنید .."></textarea>
            </div>

          </div>
        </div>
        <div class="col-md-6">

          <div class="row mb-5">
            <div class="col-md-12">
              <h2 class="h3 mb-3 text-black">کد تخفیف :</h2>
              <div class="p-3 p-lg-5 border bg-white">

                <label for="c_code" class="text-black mb-3">کد تخفیف خود را وارد کنید ..</label>
                <div class="input-group w-75 couponcode-wrap">
                  <input type="text" class="form-control me-2" id="coupon_code" name="coupon" placeholder="کد تخفیف" aria-label="Coupon Code" aria-describedby="button-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary btn-sm" onclick="ValidationCoupon()" type="button">اعمال تخفیف</button>
                  </div>
                </div>

              </div>
            </div>
          </div>

          <div class="row mb-5">
            <div class="col-md-12">
              <h2 class="h3 mb-3 text-black">سفارشات شما</h2>
              <div class="p-3 p-lg-5 border bg-white">
                <table class="table site-block-order-table mb-5">
                  <thead>
                    <th>محصول</th>
                    <th>مبلغ کل</th>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Top Up T-Shirt <strong class="mx-2">x</strong> 1</td>
                      <td>$250.00</td>
                    </tr>
                    <tr>
                      <td>Polo Shirt <strong class="mx-2">x</strong>   1</td>
                      <td>$100.00</td>
                    </tr>
                    <tr class="m-3">
                      <td class="text-black font-weight-bold"><strong>جمع سبد خرید :</strong></td>
                      <td class="text-black" id="total_price">{{ total_price|intcomma }}</td>
                    </tr>
                    <tr>
                      <td class="text-black font-weight-bold"><strong>مالیات :</strong></td>
                      <td class="text-black" id="total_tax">{{ total_tax|intcomma }}</td>
                    </tr>
                    <tr>
                      <td class="text-black font-weight-bold"><strong>جمع کل :</strong></td>
                      <td class="text-black font-weight-bold" id="total_payment_price"><strong>{{ total_payment_price|intcomma }}</strong></td>
                    </tr>
                  </tbody>
                </table>

                <select name="" id="" class="form-select form-select-sm text-center mb-3">
                  <option selected>نحوه پرداخت مبلغ</option>
                  <option value="1">پرداخت از کیف پول</option>
                  <option value="2">پرداخت آنلاین</option>
                  <option value="">پرداخت درب محل</option>
                </select>

                <div class="form-group">
                  <button class="btn btn-black btn-lg py-3 btn-primary" form="checkoutform">سفارش دهید</button>
                </div>

              </div>
            </div>
          </div>

        </div>
      </div>
    </form>

      <!-- </form> -->
    </div>
  </div>


{% endblock %}


{% block extra_js %}
{% for item in addressess %}
<script>
  // تعریف دیکشنری آدرس‌ها در جاوااسکریپت
  const addresses = {
      {% for address in addressess %}
          "{{ address.id }}": {
              address: "{{ address.address }}",
              state: "{{ address.state }}",
              zip_code: "{{ address.zip_code }}"
          }{% if not loop.last %},{% endif %}
      {% endfor %}
  };

  $(document).ready(function() {
      $("#address_id").on("change", function () {
          const selectedId = $(this).val();

          if (addresses[selectedId]) {
              $("#address_address").val(addresses[selectedId].address);
              $("#address_city").val(addresses[selectedId].state);
              $("#address_zip_code").val(addresses[selectedId].zip_code);
          } else {
              // اگر گزینه‌ای غیر معتبر یا انتخاب نشده بود، فیلدها رو پاک کن
              $("#address_address").val("");
              $("#address_city").val("");
              $("#address_zip_code").val("");
          }
      });
  });
</script>

{% endfor %}
<script>

   function applyDiscount(total_price, total_tax, total_payment_price) {
      const formatter = new Intl.NumberFormat();

      const formattedPrice = formatter.format(total_price);
      const formattedTax = formatter.format(total_tax);
      const formattedPaymentPrice = formatter.format(total_payment_price);

      $("#total_tax").html(formattedTax);
      $("#total_price").html(formattedPrice);
      $("#total_payment_price").html(formattedPaymentPrice);
  }
  function ValidationCoupon(){
    let coupon = $("#coupon_code").val()
    $.ajax({
      url: "{% url 'order:validation-coupon' %}",
      method:"POST",
      data: {
        coupon:coupon,
        csrfmiddlewaretoken:"{{ csrf_token }}"
      },
      success: function (response){
        Toastify({
          text:response.message,
          className: `info`,
          style: {
            background: "blue",
          }
        }).showToast();
        applyDiscount(response.total_price,response.total_tax, response.total_payment_price)

      },
      error: function (jqXHR, textStatus, errorThrown) {
          Toastify({
              text:jqXHR.responseJSON.message,
              className: `error`,
              style: {
                background: "red",
              }
            }).showToast();
          
            }
    });
  };

</script>


{% endblock %}

core/templates/order/completed.html
{% extends 'base.html' %}
{% load static %}


{% block extra_css %}{% endblock %}



{% block content %}

        

		<div class="untree_co-section">
            <div class="container">
              <div class="row">
                <div class="col-md-12 text-center pt-5">
                  <span class="display-3 thankyou-icon text-primary">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                      <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                  </span>
                  <h2 class="display-3 text-black">تشکر از شما:</h2>
                  <p class="lead mb-5">سفارش شما با موفقیت انجام شد .</p>
                  <p><a href="{% url 'shop:product-grid' %}" class="btn btn-sm btn-outline-black">بازگشت به محصولات</a></p>
                </div>
              </div>
            </div>
          </div>
        

{% endblock %}




{% block extra_js %}{% endblock %}

core/templates/order/failed.html
{% extends 'base.html' %}
{% load static %}


{% block extra_css %}{% endblock %}



{% block content %}

        

		<div class="untree_co-section">
            <div class="container">
              <div class="row">
                <div class="col-md-12 text-center pt-5">
                  <span class="display-3 thankyou-icon text-danger">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                      <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    
                    </svg>
                  </span>
                  <h2 class="display-3 text-black">پرداخت شما لغو شد</h2>
                  <p class="lead mb-5">دلیل خود را با ما به اشتراک بگذارید ..</p>
                  <p><a href="{% url 'shop:product-grid' %}" class="btn btn-sm btn-outline-black">بازگشت به محصولات</a></p>
                </div>
              </div>
            </div>
          </div>
        

{% endblock %}




{% block extra_js %}{% endblock %}